version: '3'
services: 
    api-service:
        build: api/
        expose: 
            - "8003"
        ports: 
            - "8003:8003"
        command: gunicorn app:app --bind 0.0.0.0:8003 --timeout 1200 -w 1 -k uvicorn.workers.UvicornWorker

    web-service:
        build: web/
        expose: 
            - "8004"
        ports: 
            - "80:8004"
        command: streamlit run web/app.py
