# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cassava-api

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_723b9d1b97984950b879b27d04a278c3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f16c9bf612e6491b81fee2c6f691f196 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_723b9d1b97984950b879b27d04a278c3 }}/psvishnu / cassava_api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cassava-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_17b383873f41424d9eb82b2833920b49 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_723b9d1b97984950b879b27d04a278c3 }}/psvishnu / cassava_api:${{ github.sha }}'